plugins {
    id 'dev.architectury.loom-no-remap' version '1.14-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.5-SNAPSHOT'
}

architectury {
    minecraft = project.minecraft_version
}

subprojects {
    if (it.name != "neoforge_coremods") {
        apply plugin: "dev.architectury.loom-no-remap"
    }

    repositories {
        maven { url "https://maven.terraformersmc.com/" }
        maven { url "https://maven.isxander.dev/releases" }
        maven { url "https://maven.neoforged.net/releases/" }
    }
}

allprojects {
    apply plugin: 'java'

    version = rootProject.mod_version

    base {
        archivesName = rootProject.archives_name
    }

    group = rootProject.maven_group

    if (it.name != "neoforge_coremods") {
        apply plugin: 'architectury-plugin'
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 25
    }
}
